export const navLinks = [
  {
    title: "Home",
    url: "/",
    icon: "home",
    color: 1,
  },
  {
    title: "Events",
    url: "/Events",
    icon: "Events",
    color: 2,
  },
  {
    title: "Reminders",
    url: "/Reminders",
    icon: "Reminders",
    color: 3,
  },
  {
    title: "UseFul Links",
    url: "/useful",
    icon: "useful",
    color: 4,
  },
];

export const EventList = [
  {
    title: "Community BBQ",
    body: "Join us for a fun-filled community BBQ with food, games, and music!",
    location: "Central Park",
    author: "John Doe",
    date: "Thursday, August 15, 2024",
    image: "https://assets.aceternity.com/demos/babbu-maan.jpeg",
    bg_color: "bg-blue-100",
  },
  {
    title: "Outdoor Movie Night",
    body: "Bring your blankets and chairs for a movie under the stars. We'll be showing 'The Greatest Showman'.",
    location: "Greenwood Park",
    author: "Jane Smith",
    date: "Tuesday, August 20, 2024",
    image: "https://assets.aceternity.com/demos/babbu-maan.jpeg",
    bg_color: "bg-purple-100",
  },
  {
    title: "Farmers Market",
    body: "Come and enjoy fresh produce, handmade crafts, and live music at our weekly farmers market.",
    location: "Market Square",
    author: "Market Committee",
    date: "Monday, August 12, 2024",
    image: "https://assets.aceternity.com/demos/babbu-maan.jpeg",
    bg_color: "bg-green-100",
  },
  {
    title: "Charity Fun Run",
    body: "Participate in our charity fun run to raise money for local schools. All ages welcome!",
    location: "Riverside Park",
    author: "Local Schools Fund",
    date: "Sunday, August 18, 2024",
    image: "https://assets.aceternity.com/demos/babbu-maan.jpeg",
    bg_color: "bg-yellow-100",
  },
  {
    title: "Art in the Park",
    body: "Enjoy a day of art exhibits, workshops, and performances by local artists.",
    location: "Artisan Park",
    author: "Art Association",
    date: "Thursday, August 22, 2024",
    image: "https://assets.aceternity.com/demos/babbu-maan.jpeg",
    bg_color: "bg-pink-100",
  },
  {
    title: "Neighborhood Cleanup",
    body: "Join us for a community cleanup day to keep our neighborhood beautiful. Supplies provided.",
    location: "Main Street",
    author: "Green Initiative",
    date: "Monday, August 19, 2024",
    image: "https://assets.aceternity.com/demos/babbu-maan.jpeg",
    bg_color: "bg-teal-100",
  },
  {
    title: "Book Club Meeting",
    body: "Discuss this month's book, 'The Night Circus', with fellow book lovers. Snacks provided.",
    location: "Community Library",
    author: "Book Club",
    date: "Saturday, August 17, 2024",
    image: "https://assets.aceternity.com/demos/babbu-maan.jpeg",
    bg_color: "bg-indigo-100",
  },
  {
    title: "Summer Concert Series",
    body: "Enjoy live music every Saturday evening in the park. This week's band: The Rockers.",
    location: "Music Pavilion",
    author: "City Events",
    date: "Saturday, August 24, 2024",
    image: "https://assets.aceternity.com/demos/babbu-maan.jpeg",
    bg_color: "bg-orange-100",
  },
  {
    title: "Pet Adoption Fair",
    body: "Find your new best friend at our pet adoption fair. Adoption fees waived for the day!",
    location: "Animal Shelter",
    author: "Animal Rescue",
    date: "Wednesday, August 21, 2024",
    image: "https://assets.aceternity.com/demos/babbu-maan.jpeg",
    bg_color: "bg-gray-100",
  },
  {
    title: "Gardening Workshop",
    body: "Learn the basics of gardening from local experts. Free starter kits for all attendees.",
    location: "Community Garden",
    author: "Gardening Club",
    date: "Friday, August 23, 2024",
    image: "https://assets.aceternity.com/demos/babbu-maan.jpeg",
    bg_color: "bg-lime-100",
  },
];

export const Days = [
  {
    number: 1,
    day: "Monday",
    pickUp: ["recycling", "garbage"],
  },
  {
    number: 2,
    day: "Tuesday",
    pickUp: ["yard waste"],
  },
  {
    number: 3,
    day: "Wednesday",
    pickUp: ["recycling"],
  },
  {
    number: 4,
    day: "Thursday",
    pickUp: ["garbage"],
  },
  {
    number: 5,
    day: "Friday",
    pickUp: ["yard waste", "recycling"],
  },
];
